
FROM node:16-slim

WORKDIR /app
RUN mkdir files
ENV PORT 8005
ENV CONTEXT_PATH /review-service/api
ENV MONGO_DB_URI mongodb://prodUser:prodUser123!4_lp1c_0999@10.14.26.226:27017/zalon-prod-db
ENV JWT_KEY d79cf0a6eef210824bbfd374630dd461b3bc11d24897b7b1d1333473328b48280a6c1d8c2122ac1faafc
COPY package.json .

RUN npm install --omit=dev

RUN npm install pm2 -g

COPY . .

EXPOSE 8005

CMD ["pm2-runtime", "src/index.js"]
