name: Update CODEOWNERS

on:
  push:
    branches:
      - PR-restrict
  workflow_dispatch:

jobs:
  update-codeowners:
    runs-on: ubuntu-latest

    env:
      GH_OWNER: "rahulkkkhatri" # Replace with your GitHub username
      GH_TOKEN: ${{ secrets.GH_PAT }}
      EXCLUDED_REPO: "b2b-review-service" # Replace with the name of the repo to exclude

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Git configuration
        run: |
          git config --global user.name "rahulkkkhatri"
          git config --global user.email "rahul.khatri10101@gmail.com"

      - name: Update CODEOWNERS in Repositories
        run: |
          # Fetch the list of repositories
          repos=$(curl -H "Authorization: token $GH_TOKEN" "https://api.github.com/users/$GH_OWNER/repos" | jq -r '.[].name')

          # Loop through each repository
          for repo in $repos; do
            if [ "$repo" != "$EXCLUDED_REPO" ]; then
              # Clone the repository
              git clone https://$GH_OWNER:$GH_TOKEN@github.com/$GH_OWNER/$repo.git
              cd $repo

              # Create the .github directory and CODEOWNERS file
              mkdir -p .github
              echo -e "# Add your CODEOWNERS content here\n* @$GH_OWNER" > .github/CODEOWNERS

              # Commit and push changes
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add .github/CODEOWNERS
              git commit -m "Add CODEOWNERS file"
              git push origin main

              # Return to the root directory and clean up
              cd ..
              rm -rf $repo
            fi
          done
      

      